### PR TITLE
Update for Minecraft Version 1.20.4

### LINKED ISSUE #17: 1.20 Experimental Hotfixes (1.20.2+)
This is a feature request.

### PR DESCRIPTION
**Pull request by LeBogoo**
This pull request addresses several issues and updates for the Inventory Tabs Minecraft Mod.

## Changes:

- Updated mod to be compatible with Minecraft Version 1.20.4.
- Fixed positioning issues occurring in 6-row inventories.
- Resolved the broken ControlHintToast, ensuring proper functionality.

These changes primarily focus on compatibility updates and bug fixes.

This PR should resolve #17 and #35.

### CODE REVIEW

**Comment by K9Paradox** [comment]
I love you :) 
Thank you for adding support.

**Comment by sleepingdragoninn** [comment]
Heya! I've spun up an experimental hotfixes policy in #43 - basically, we want to keep this off the modrinth page and the main source to avoid clutter - but we'd like to compile it ourselves, publish it as a github release, and post it in #43.

Later, when we update to 1.21, we'll likely cherry pick / coauthor you in these changes where they're still relevant.

Let me know if you're happy with that arrangement! Otherwise we'll soldier through the 1.21 port alone when the time comes

**Comment by LeBogoo** [comment]
Yeah, I'm happy with that solution.
I'm always happy to help!

**Review by sleepingdragoninn — CHANGES_REQUESTED** [review]
Looks like the fixes aren't quite right.

Tab rendering:

image

Selected tab doesn't appear on top of the inventory, tabs have an incorrect height + width.
Additionally, crunching (our simplified version of 9slice) seems broken - the right hand side of the tab is being cut off.

Container screen:

java_WmIWF4ruUC

Screen is offset noticeably compared to other screens, even with the fix for this enabled.

I'd recommend scrapping changes to `Tab` and `DrawUtil` and pulling in latest, as we've made some notable improvements to clarity of what each adjustment to u, v, height, etc, is actually for. Also inverted tabs are easy to enable now, so you'll be able to test those.

**Comment by sleepingdragoninn** [comment]
When making tab rendering adjustments, make sure you use original version screenshots as a reference:

7feef9e9ba223616e0462725ea7f5d860aea946f


90d111b2eb482c29cdf7cfaf20ca8f9a758d78a4

As mentioned, there's no pressure to get this done - if it gets done, we'll publish it and use it as a reference, but we'll handle our 1.21 update either way.

**Comment by Athar42** [comment]
Just want to add a comment on this PR, used with the base 1.1.8 release, there seems to be a little bug while interracting with a chest (or any container).

For example, open a chest then left click any item present in the hotbar, and it will be drop to the ground.
Having multiple items stacked, they will drop one at a time (just like if you were having the mouse over the item, and used the binded key to drop the item).

When I disable this modified mod, it's working fine again, so that's just a bug report for that PR, so anyone is aware of it :)

PS : This could be a conflicting mod too, but I don't see which one could do that.

**Comment by CamoGuy3000** [comment]
I don't know how much of an ask this is, but what would it take to get an update to 1.20.6? And if there are any, what resources could I look into to see if I could do this myself?

**Comment by sleepingdragoninn** [comment]
closing this as we've [ported to 1.21](https://github.com/sisby-folk/inventory-tabs/commit/53b578249d1d6f5c54c661e45d33edcaf382016f) now. 

image

**Comment by RWTAMIR** [comment]
HOW TO DOWNLOAD  THE MOD

**Pull request closed without merging**
